# configs/your_action_config.yaml


# ===== 数据集设置 =====
dataset:
  train_dir: data/train
  val_dir:   data/val
  test_dir:  data/test

  # label_map: # 12
  #   Align_screwdriver:     0
  #   Approach:              1
  #   Idle:                  2
  #   No_human:              3
  #   Pick_bolt:             4
  #   Pick_cover:            5
  #   Pick_screwdriver:      6
  #   Place_bolt:            7
  #   Place_cover:           8
  #   Put_down_screwdriver:  9
  #   Screw:                10
  #   Transition:           11

  # label_map: # 10
  #   Align_screwdriver:     0
  #   Approach:              1
  #   Pick_bolt:             2
  #   Pick_cover:            3
  #   Pick_screwdriver:      4
  #   Place_bolt:            5
  #   Place_cover:           6
  #   Put_down_screwdriver:  7
  #   Screw:                 8
  #   Transition:            9

  # label_map: # 0428 6种
  #   Approach:                    0
  #   Pick_and_Place_Bolt:         1
  #   Pick_and_Place_Cover:        2
  #   Pick_and_Place_Screwdriver:  3
  #   Screw:                       4
  #   Transition:                  5

  label_map: # 0628 8种
    Approach:                    0
    Pick_and_Place_Bolt:         1
    Pick_and_Place_Cover:        2
    Pick_and_Place_Part1_Small:  3
    Pick_and_Place_Part2_Big:    4
    Pick_and_Place_Screwdriver:  5
    Screw:                       6
    Transition:                  7

  window_size:             9         # 定长帧数
  stride:                  3         # 滑动步长
  enable_transform:        true      # 是否启用数据变换
  
  window_size_us:          333333    # 单位微秒us, (333333/1000000)* 30fps = 10帧
  stride_us:               66666     # 单位微秒us, (66666/1000000)* 30fps = 2帧
  max_points:              8192      # 点云最大点数 4096 8192
  time_dimension:          true      # 是否使用时间维度
  enable_augment:          false     # 是否启用数据增强
  t_squash_factor:         3333      # 每t_squash_factor微秒内的时间戳表示成一个时间戳
  target_width:            346       # 目标图像宽度 346 256 128
  target_height:           260       # 目标图像高度 260 192 96
  min_events_per_window:   4000      # 一个时间窗口中最小事件数阈值

  window_size_event_count: 32768     # 窗口包含的事件数,可选: 8192, 16384, 32768
  step_size:               4096      # 滑动窗口步长（事件数）可选: 1024, 2048, 4096, 8192
  denoise:                 true      # 是否执行降噪
  denoise_method:          'voxel'   # 降噪方法: 'density', 'dbscan', 'voxel', 'histogram', 'random', 'temporal'
  denoise_radius:          0.05      # 降噪搜索半径
  voxel_size_txy:          [1000, 10, 10] # 体素大小 [t, x, y] 单位: 微秒 和 像素
  min_neighbors:           5         # 最小邻居数量阈值
  denoise_threshold:       0.2       # 密度阈值参数


# ===== DataLoader 参数 =====
train:
  # ---------------------------------------
  # 32 for vit, 16 for cnn, 128 for pointnet2 in server
  # 32 or 16 for pointnet2msg in server
  batch_size:   32
  # ---------------------------------------
  num_workers:  0     # 子进程加载训练数据
  shuffle:      true

val:
  # ---------------------------------------
  batch_size:   32
  # ---------------------------------------
  num_workers:  0     
  shuffle:      false

test:
  batch_size:   16
  num_workers:  0    
  shuffle:      false


# ===== ViT模型配置 =====
vit_model:
  backbone:
    # ---------------------------------------
    img_size:    [576, 768] # [192, 256]
    patch_size:  [192, 256]
    # 4 for rgbe and rgbd, 3 for rgb, 1 for event
    in_chans:   1
    # ---------------------------------------
    num_classes: 8 # 12
    embed_dim:   384 # 768
    depth:      6 # 12
    num_heads:  6 # 12
    mlp_ratio:  3.0 # 4.
    qkv_bias:   true
    qk_scale:   null
    drop_rate:  0.2
    attn_drop_rate: 0.2
    drop_path_rate: 0.5
    hybrid_backbone: null
    norm_layer:  null
    use_checkpoint: false
    frozen_stages: -1
    ratio:       1
    last_norm:  true
    patch_padding: pad
    freeze_attn: false
    freeze_ffn:  false

  neck:
    input_dim:  384 # 768
    hidden_dim: 192 # 256
    mode: mean           # 可选：lstm / mean / none

  head:
    input_dim:    192  # 与 neck 输出一致
    num_classes:  12
    dropout_prob: 0.5


# ===== cnn模型配置 =====
cnn_model:
  # ---------------------------------------
  # 4 for rgbe and rgbd, 3 for rgb, 1 for event
  input_dim:  1          # 输入通道数
  output_dim: 12          # 输出类别数
  input_height: 192          # 输入图像高度
  input_width: 256           # 输入图像宽度
  # ---------------------------------------


# ===== pointnet2模型配置 =====
pointnet2_model:
  num_classes: 8
  normal_channel: True  # 事件数据没有法向量，相当于特征向量
  input_dim: 4  # t, x, y, p
  


# ===== 优化器 & 训练 =====
optimizer:
  type:         AdamW # 可选：SGD / Adam / AdamW
  lr:           0.0025 # 0.0001 or 2e-4 or 0.00025 or 0.01
  weight_decay: 1e-2 # 0.001 or 5e-3

epochs:   20
device:   cuda:0
work_dir: results/checkpoints
log_dir: results/logs
fig_dir: results/figs
# ---------------------------------------
model_type: pointnet2  # options: cnn / vit / pointnet2 / pointnet2msg
# ---------------------------------------
